<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Introduction to the North Carolina SIDS data set (revised) • spdep</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Introduction to the North Carolina SIDS data set (revised)">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">spdep</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.0.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/CO69.html">“The Problem of Spatial Autocorrelation:” forty years on</a>
    </li>
    <li>
      <a href="../articles/SpatialFiltering.html">Moran Eigenvectors</a>
    </li>
    <li>
      <a href="../articles/nb_igraph.html">Spatial weights objects as sparse matrices and graphs</a>
    </li>
    <li>
      <a href="../articles/nb_sf.html">Creating Neighbours using sf objects</a>
    </li>
    <li>
      <a href="../articles/sids.html">Introduction to the North Carolina SIDS data set (revised)</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/r-spatial/spdep">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Introduction to the North Carolina SIDS data set (revised)</h1>
                        <h4 class="author">Roger Bivand</h4>
            
      
      <small class="dont-index">Source: <a href="https://github.com/r-spatial/spdep/blob/master/vignettes/sids.Rmd"><code>vignettes/sids.Rmd</code></a></small>
      <div class="hidden name"><code>sids.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>This data set was presented first in <span class="citation">Symons, Grimson, and Yuan (1983)</span>, analysed with reference to the spatial nature of the data in <span class="citation">Cressie and Read (1985)</span>, expanded in <span class="citation">Cressie and Chan (1989)</span>, and used in detail in <span class="citation">Cressie (1991)</span>. It is for the 100 counties of North Carolina, and includes counts of numbers of live births (also non-white live births) and numbers of sudden infant deaths, for the July 1, 1974 to June 30, 1978 and July 1, 1979 to June 30, 1984 periods. In <span class="citation">Cressie and Read (1985)</span>, a listing of county neighbours based on shared boundaries (contiguity) is given, and in <span class="citation">Cressie and Chan (1989)</span>, and in <span class="citation">Cressie (1991, 386–89)</span>, a different listing based on the criterion of distance between county seats, with a cutoff at 30 miles. The county seat location coordinates are given in miles in a local (unknown) coordinate reference system. The data are also used to exemplify a range of functions in the spatial statistics module user’s manual <span class="citation">(Kaluzny et al. 1996)</span>.</p>
</div>
<div id="getting-the-data-into-r" class="section level2">
<h2 class="hasAnchor">
<a href="#getting-the-data-into-r" class="anchor"></a>Getting the data into R</h2>
<p>We will be using the <strong>spdep</strong> package, here version: spdep, version 1.0-1, 2019-01-21, the <strong>sp</strong> package and the <strong>maptools</strong> package. The data from the sources refered to above is documented in the help page for the <code>nc.sids</code> data set in <strong>spData</strong>. The actual data, included in a shapefile of the county boundaries for North Carolina has been made available in the <strong>maptools</strong> package.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> These data are known to be geographical coordinates (longitude-latitude in decimal degrees) and are assumed to use the NAD27 datum.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(sp)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(spdep)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="cf">if</span> (<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(rgdal, <span class="dt">quietly=</span><span class="ot">TRUE</span>)) {</a>
<a class="sourceLine" id="cb1-4" data-line-number="4">  nc &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/rgdal/topics/readOGR">readOGR</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/system.file">system.file</a></span>(<span class="st">"shapes/sids.shp"</span>, <span class="dt">package=</span><span class="st">"spData"</span>)[<span class="dv">1</span>])</a>
<a class="sourceLine" id="cb1-5" data-line-number="5">} <span class="cf">else</span> {</a>
<a class="sourceLine" id="cb1-6" data-line-number="6">  <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(maptools, <span class="dt">quietly=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb1-7" data-line-number="7">  nc &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/maptools/topics/readShapeSpatial">readShapeSpatial</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/system.file">system.file</a></span>(<span class="st">"shapes/sids.shp"</span>, <span class="dt">package=</span><span class="st">"spData"</span>)[<span class="dv">1</span>])</a>
<a class="sourceLine" id="cb1-8" data-line-number="8">}</a></code></pre></div>
<pre><code>## OGR data source with driver: ESRI Shapefile 
## Source: "/home/rsb/lib/r_libs/spData/shapes/sids.shp", layer: "sids"
## with 100 features
## It has 22 fields</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/is.projected">proj4string</a></span>(nc) &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/CRS-class">CRS</a></span>(<span class="st">"+proj=longlat +datum=NAD27"</span>)</a>
<a class="sourceLine" id="cb3-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/row.names">row.names</a></span>(nc) &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/character">as.character</a></span>(nc<span class="op">$</span>FIPSNO)</a></code></pre></div>
<p>The shapefile format presupposes that you have three files with extensions <code>.shp</code>, <code>.shx</code>, and <code>.dbf</code>, where the first contains the geometry data, the second the spatial index, and the third the attribute data. They are required to have the same name apart from the extension, and are read here using <code><a href="https://www.rdocumentation.org/packages/maptools/topics/readShapeSpatial">readShapeSpatial()</a></code> into the <code>SpatialPolygonsDataFrame</code> object <code>nc</code>; the class is defined in <strong>sp</strong>. The centroids of the largest polygon in each county are available using the <code>coordinates</code> method from <strong>sp</strong> as a two-column matrix, and can be used to place labels:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(nc, <span class="dt">axes=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb4-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/gridlines">text</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/coordinates">coordinates</a></span>(nc), <span class="dt">label=</span>nc<span class="op">$</span>FIPSNO, <span class="dt">cex=</span><span class="fl">0.5</span>)</a></code></pre></div>
<p><img src="sids_files/figure-html/unnamed-chunk-3-1.png" width="700"></p>
<p>We can examine the names of the columns of the data frame to see what it contains — in fact some of the same columns that we will be examining below, and some others which will be useful in cleaning the data set.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/names">names</a></span>(nc)</a></code></pre></div>
<pre><code>##  [1] "CNTY_ID"   "AREA"      "PERIMETER" "CNTY_"     "NAME"     
##  [6] "FIPS"      "FIPSNO"    "CRESS_ID"  "BIR74"     "SID74"    
## [11] "NWBIR74"   "BIR79"     "SID79"     "NWBIR79"   "east"     
## [16] "north"     "x"         "y"         "lon"       "lat"      
## [21] "L_id"      "M_id"</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary</a></span>(nc)</a></code></pre></div>
<pre><code>## Object of class SpatialPolygonsDataFrame
## Coordinates:
##         min       max
## x -84.32385 -75.45698
## y  33.88199  36.58965
## Is projected: FALSE 
## proj4string :
## [+proj=longlat +datum=NAD27 +ellps=clrk66
## +nadgrids=@conus,@alaska,@ntv2_0.gsb,@ntv1_can.dat]
## Data attributes:
##     CNTY_ID          AREA          PERIMETER         CNTY_     
##  Min.   :1825   Min.   :0.0420   Min.   :0.999   Min.   :1825  
##  1st Qu.:1902   1st Qu.:0.0910   1st Qu.:1.324   1st Qu.:1902  
##  Median :1982   Median :0.1205   Median :1.609   Median :1982  
##  Mean   :1986   Mean   :0.1263   Mean   :1.673   Mean   :1986  
##  3rd Qu.:2067   3rd Qu.:0.1542   3rd Qu.:1.859   3rd Qu.:2067  
##  Max.   :2241   Max.   :0.2410   Max.   :3.640   Max.   :2241  
##                                                                
##         NAME         FIPS        FIPSNO         CRESS_ID     
##  Alamance : 1   37001  : 1   Min.   :37001   Min.   :  1.00  
##  Alexander: 1   37003  : 1   1st Qu.:37050   1st Qu.: 25.75  
##  Alleghany: 1   37005  : 1   Median :37100   Median : 50.50  
##  Anson    : 1   37007  : 1   Mean   :37100   Mean   : 50.50  
##  Ashe     : 1   37009  : 1   3rd Qu.:37150   3rd Qu.: 75.25  
##  Avery    : 1   37011  : 1   Max.   :37199   Max.   :100.00  
##  (Other)  :94   (Other):94                                   
##      BIR74           SID74          NWBIR74           BIR79      
##  Min.   :  248   Min.   : 0.00   Min.   :   1.0   Min.   :  319  
##  1st Qu.: 1077   1st Qu.: 2.00   1st Qu.: 190.0   1st Qu.: 1336  
##  Median : 2180   Median : 4.00   Median : 697.5   Median : 2636  
##  Mean   : 3300   Mean   : 6.67   Mean   :1051.0   Mean   : 4224  
##  3rd Qu.: 3936   3rd Qu.: 8.25   3rd Qu.:1168.5   3rd Qu.: 4889  
##  Max.   :21588   Max.   :44.00   Max.   :8027.0   Max.   :30757  
##                                                                  
##      SID79          NWBIR79             east           north      
##  Min.   : 0.00   Min.   :    3.0   Min.   : 19.0   Min.   :  6.0  
##  1st Qu.: 2.00   1st Qu.:  250.5   1st Qu.:178.8   1st Qu.: 97.0  
##  Median : 5.00   Median :  874.5   Median :285.0   Median :125.5  
##  Mean   : 8.36   Mean   : 1352.8   Mean   :271.3   Mean   :122.1  
##  3rd Qu.:10.25   3rd Qu.: 1406.8   3rd Qu.:361.2   3rd Qu.:151.5  
##  Max.   :57.00   Max.   :11631.0   Max.   :482.0   Max.   :182.0  
##                                                                   
##        x                 y             lon              lat       
##  Min.   :-328.04   Min.   :3757   Min.   :-84.08   Min.   :33.92  
##  1st Qu.: -60.55   1st Qu.:3920   1st Qu.:-81.20   1st Qu.:35.26  
##  Median : 114.38   Median :3963   Median :-79.26   Median :35.68  
##  Mean   :  91.46   Mean   :3953   Mean   :-79.51   Mean   :35.62  
##  3rd Qu.: 240.03   3rd Qu.:4000   3rd Qu.:-77.87   3rd Qu.:36.05  
##  Max.   : 439.65   Max.   :4060   Max.   :-75.67   Max.   :36.52  
##                                                                   
##       L_id           M_id     
##  Min.   :1.00   Min.   :1.00  
##  1st Qu.:1.00   1st Qu.:2.00  
##  Median :2.00   Median :3.00  
##  Mean   :2.12   Mean   :2.67  
##  3rd Qu.:3.00   3rd Qu.:3.25  
##  Max.   :4.00   Max.   :4.00  
## </code></pre>
<p>We will now examine the data set reproduced from Cressie and collaborators, included in <strong>spdep</strong>, and add the neighbour relationships used in <span class="citation">Cressie and Chan (1989)</span> to the background map as a graph shown in Figure :</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1">gal_file &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/system.file">system.file</a></span>(<span class="st">"weights/ncCR85.gal"</span>, <span class="dt">package=</span><span class="st">"spData"</span>)[<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb9-2" data-line-number="2">ncCR85 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/read.gal.html">read.gal</a></span>(gal_file, <span class="dt">region.id=</span>nc<span class="op">$</span>FIPSNO)</a>
<a class="sourceLine" id="cb9-3" data-line-number="3">ncCR85</a></code></pre></div>
<pre><code>## Neighbour list object:
## Number of regions: 100 
## Number of nonzero links: 492 
## Percentage nonzero weights: 4.92 
## Average number of links: 4.92</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1">gal_file &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/system.file">system.file</a></span>(<span class="st">"weights/ncCC89.gal"</span>, <span class="dt">package=</span><span class="st">"spData"</span>)[<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb11-2" data-line-number="2">ncCC89 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/read.gal.html">read.gal</a></span>(gal_file, <span class="dt">region.id=</span>nc<span class="op">$</span>FIPSNO)</a>
<a class="sourceLine" id="cb11-3" data-line-number="3">ncCC89</a></code></pre></div>
<pre><code>## Neighbour list object:
## Number of regions: 100 
## Number of nonzero links: 394 
## Percentage nonzero weights: 3.94 
## Average number of links: 3.94 
## 2 regions with no links:
## 37055 37095</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(nc, <span class="dt">border=</span><span class="st">"grey"</span>)</a>
<a class="sourceLine" id="cb13-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(ncCC89, <span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/coordinates">coordinates</a></span>(nc), <span class="dt">add=</span><span class="ot">TRUE</span>, <span class="dt">col=</span><span class="st">"blue"</span>)</a></code></pre></div>
<p>Printing the neighbour object shows that it is a neighbour list object, with a very sparse structure — if displayed as a matrix, only 3.94% of cells would be filled. Objects of class <span><code>nb</code></span> contain a list as long as the number of counties; each component of the list is a vector with the index numbers of the neighbours of the county in question, so that the neighbours of the county with <span><code>region.id</code></span> of <span><code>37001</code></span> can be retreived by matching against the indices. More information can be obtained by using <span><code><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary()</a></code></span> on an <span><code>nb</code></span> object. Finally, we associate a vector of names with the neighbour list, through the <span><code>row.names</code></span> argument. The names should be unique, as with data frame row names.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1">ncCC89</a></code></pre></div>
<pre><code>## Neighbour list object:
## Number of regions: 100 
## Number of nonzero links: 394 
## Percentage nonzero weights: 3.94 
## Average number of links: 3.94 
## 2 regions with no links:
## 37055 37095</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1">r.id &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/attr">attr</a></span>(ncCC89, <span class="st">"region.id"</span>)</a>
<a class="sourceLine" id="cb16-2" data-line-number="2">ncCC89[[<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/match">match</a></span>(<span class="st">"37001"</span>, r.id)]]</a></code></pre></div>
<pre><code>## [1] 11 26 29 30 48</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1">r.id[ncCC89[[<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/match">match</a></span>(<span class="st">"37001"</span>, r.id)]]]</a></code></pre></div>
<pre><code>## [1] 37033 37081 37135 37063 37037</code></pre>
<p>The neighbour list object records neighbours by their order in relation to the list itself, so the neighbours list for the county with <span><code>region.id</code></span> “37001” are the seventeenth, nineteenth, thirty-second, forty-first and sixty-eighth in the list. We can retreive their codes by looking them up in the <span><code>region.id</code></span> attribute.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/character">as.character</a></span>(nc<span class="op">$</span>NAME)[<span class="kw"><a href="../reference/card.html">card</a></span>(ncCC89) <span class="op">==</span><span class="st"> </span><span class="dv">0</span>]</a></code></pre></div>
<pre><code>## [1] "Dare" "Hyde"</code></pre>
<p>We should also note that this neighbour criterion generates two counties with no neighbours, Dare and Hyde, whose county seats were more than 30 miles from their nearest neighbours. The <span><code><a href="../reference/card.html">card()</a></code></span> function returns the cardinality of the neighbour set. We need to return to methods for handling no-neighbour objects later on. We will also show how new neighbours lists may be constructed in , and compare these with those from the literature.</p>
<div id="probability-mapping" class="section level3">
<h3 class="hasAnchor">
<a href="#probability-mapping" class="anchor"></a>Probability mapping</h3>
<p>Rather than review functions for measuring and modelling spatial dependence in the <strong>spdep</strong> package, we will focus on probability mapping for disease rates data. Typically, we have counts of the incidence of some disease by spatial unit, associated with counts of populations at risk. The task is then to try to establish whether any spatial units seem to be characterised by higher or lower counts of cases than might have been expected in general terms <span class="citation">(Bailey and Gatrell 1995)</span>.</p>
<p>An early approach by <span class="citation">Choynowski (1959)</span>, described by <span class="citation">Cressie and Read (1985)</span> and <span class="citation">Bailey and Gatrell (1995)</span>, assumes, given that the true rate for the spatial units is small, that as the population at risk increases to infinity, the spatial unit case counts are Poisson with mean value equal to the population at risk times the rate for the study area as a whole. Choynowski’s approach folds the two tails of the measured probabilities together, so that small values, for a chosen <span class="math inline">\(\alpha\)</span>, occur for spatial units with either unusually high or low rates. For this reason, the high and low counties are plotted separately in Figure .</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1">ch &lt;-<span class="st"> </span><span class="kw"><a href="../reference/choynowski.html">choynowski</a></span>(nc<span class="op">$</span>SID74, nc<span class="op">$</span>BIR74)</a>
<a class="sourceLine" id="cb22-2" data-line-number="2">nc<span class="op">$</span>ch_pmap_low &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/ifelse">ifelse</a></span>(ch<span class="op">$</span>type, ch<span class="op">$</span>pmap, <span class="ot">NA</span>)</a>
<a class="sourceLine" id="cb22-3" data-line-number="3">nc<span class="op">$</span>ch_pmap_high &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/ifelse">ifelse</a></span>(<span class="op">!</span>ch<span class="op">$</span>type, ch<span class="op">$</span>pmap, <span class="ot">NA</span>)</a>
<a class="sourceLine" id="cb22-4" data-line-number="4">prbs &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">0</span>,.<span class="dv">001</span>,.<span class="dv">01</span>,.<span class="dv">05</span>,.<span class="dv">1</span>,<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb22-5" data-line-number="5">nc<span class="op">$</span>high =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/cut">cut</a></span>(nc<span class="op">$</span>ch_pmap_high, prbs)</a>
<a class="sourceLine" id="cb22-6" data-line-number="6">nc<span class="op">$</span>low =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/cut">cut</a></span>(nc<span class="op">$</span>ch_pmap_low,prbs )</a></code></pre></div>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/spplot">spplot</a></span>(nc, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"low"</span>, <span class="st">"high"</span>), <span class="dt">col.regions=</span><span class="kw"><a href="https://www.rdocumentation.org/packages/grDevices/topics/gray.colors">grey.colors</a></span>(<span class="dv">5</span>))</a></code></pre></div>
<p><img src="sids_files/figure-html/unnamed-chunk-9-1.png" width="700"></p>
<p>For more complicated thematic maps, it may be helpful to use ColorBrewer (<a href="http://colorbrewer.org" class="uri">http://colorbrewer.org</a>) colour palettes. Here we will only use the grey sequential palette, available in R in the <strong>RColorBrewer</strong> package (the colours are copied here to avoid loading the package).</p>
<p>While the <span><code><a href="../reference/choynowski.html">choynowski()</a></code></span> function only provides the probability map values required, the <span><code><a href="../reference/probmap.html">probmap()</a></code></span> function returns raw (crude) rates, expected counts (assuming a constant rate across the study area), relative risks, and Poisson probability map values calculated using the standard cumulative distribution function <span><code><a href="https://www.rdocumentation.org/packages/stats/topics/Poisson">ppois()</a></code></span>. This does not fold the tails together, so that counties with lower observed counts than expected, based on population size, have values in the lower tail, and those with higher observed counts than expected have values in the upper tail, as Figure  shows.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1">pmap &lt;-<span class="st"> </span><span class="kw"><a href="../reference/probmap.html">probmap</a></span>(nc<span class="op">$</span>SID74, nc<span class="op">$</span>BIR74)</a>
<a class="sourceLine" id="cb24-2" data-line-number="2">nc<span class="op">$</span>pmap &lt;-<span class="st"> </span>pmap<span class="op">$</span>pmap</a>
<a class="sourceLine" id="cb24-3" data-line-number="3">brks &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">0</span>,<span class="fl">0.001</span>,<span class="fl">0.01</span>,<span class="fl">0.025</span>,<span class="fl">0.05</span>,<span class="fl">0.95</span>,<span class="fl">0.975</span>,<span class="fl">0.99</span>,<span class="fl">0.999</span>,<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb24-4" data-line-number="4"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(RColorBrewer)</a></code></pre></div>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/spplot">spplot</a></span>(nc, <span class="st">"pmap"</span>, <span class="dt">at=</span>brks, <span class="dt">col.regions=</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rev">rev</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/RColorBrewer/topics/ColorBrewer">brewer.pal</a></span>(<span class="dv">9</span>, <span class="st">"RdBu"</span>)))</a></code></pre></div>
<p><img src="sids_files/figure-html/unnamed-chunk-11-1.png" width="700"></p>
<p>Marilia Carvalho (personal communication) and Virgilio Gómez Rubio <span class="citation">(Gómez-Rubio, Ferrándiz-Ferragud, and López-Quílez 2005)</span> have pointed to the unusual shape of the distribution of the Poisson probability values (Figure ), repeating the doubts about probability mapping voiced by <span class="citation">Cressie (1991, 392)</span>: “an extreme value <span class="math inline">\(\ldots\)</span> may be more due to its lack of fit to the Poisson model than to its deviation from the constant rate assumption”. There are many more high values than one would have expected, suggesting perhaps overdispersion, that is that the ratio of the variance and mean is larger than unity.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/hist">hist</a></span>(nc<span class="op">$</span>pmap, <span class="dt">main=</span><span class="st">""</span>)</a></code></pre></div>
<p>One ad-hoc way to assess the impact of the possible failure of our assumption that the counts follow the Poisson distribution is to estimate the dispersion by fitting a generalized linear model of the observed counts including only the intercept (null model) and offset by the observed population at risk (suggested by Marilia Carvalho and associates):</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1">res &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/glm">glm</a></span>(SID74 <span class="op">~</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/offset">offset</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Log">log</a></span>(BIR74)), <span class="dt">data=</span>nc, <span class="dt">family=</span><span class="st">"quasipoisson"</span>)</a>
<a class="sourceLine" id="cb27-2" data-line-number="2">nc<span class="op">$</span>stdres &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/influence.measures">rstandard</a></span>(res)</a>
<a class="sourceLine" id="cb27-3" data-line-number="3">brks &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="op">-</span><span class="dv">4</span>, <span class="dv">-3</span>, <span class="dv">-2</span>, <span class="fl">-1.5</span>, <span class="dv">-1</span>, <span class="fl">-0.5</span>, <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="fl">1.5</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>)</a></code></pre></div>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/spplot">spplot</a></span>(nc, <span class="st">"stdres"</span>, <span class="dt">at=</span>brks, <span class="dt">col.regions=</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rev">rev</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/RColorBrewer/topics/ColorBrewer">brewer.pal</a></span>(<span class="dv">11</span>, <span class="st">"RdBu"</span>)))</a></code></pre></div>
<p><img src="sids_files/figure-html/unnamed-chunk-13-1.png" width="700"></p>
<p>The dispersion is equal to 2.2786, much greater than unity; we calculate the corrected probability map values by taking the standardised residuals of the model, taking the size of the dispersion into account; the results are shown in Figure . Many fewer counties appear now to have unexpectedly large or small numbers of cases. This is an ad-hoc adjustment made because R provides access to a wide range of model-fitting functions that can be used to help check our assumptions. <span class="citation">Gómez-Rubio, Ferrándiz-Ferragud, and López-Quílez (2005)</span> chose rather to construct a probability map under the hypothesis that data are drawn from a Negative Binomial distribution.</p>
<p>So far, none of the maps presented have made use of the spatial dependence possibly present in the data. A further elementary step that can be taken is to map Empirical Bayes estimates of the rates, which are smoothed in relation to the raw rates. The underlying question here is linked to the larger variance associated with rate estimates for counties with small populations at risk compared with counties with large populations at risk. Empirical Bayes estimates place more credence on the raw rates of counties with large populations at risk, and modify them much less than they modify rates for small counties. In the case of small populations at risk, more confidence is placed in either the global rate for the study area as a whole, or for local Empirical Bayes estimates, in rates for a larger moving window including the neighbours of the county being estimated. The function used for this in <strong>spdep</strong> is <span><code><a href="../reference/EBlocal.html">EBlocal()</a></code></span>, initially contributed by Marilia Carvalho. It parallels a similar function in GeoDa, but uses the <span class="citation">Bailey and Gatrell (1995)</span> interpretation of <span class="citation">Marshall (1991)</span>, rather than that in GeoDa <span class="citation">(Anselin, Syabri, and Smirnov 2002)</span>.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1">global_rate &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(nc<span class="op">$</span>SID74)<span class="op">/</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(nc<span class="op">$</span>BIR74)</a>
<a class="sourceLine" id="cb29-2" data-line-number="2">nc<span class="op">$</span>Expected &lt;-<span class="st"> </span>global_rate <span class="op">*</span><span class="st"> </span>nc<span class="op">$</span>BIR74</a>
<a class="sourceLine" id="cb29-3" data-line-number="3">res &lt;-<span class="st"> </span><span class="kw"><a href="../reference/EBlocal.html">EBlocal</a></span>(nc<span class="op">$</span>SID74, nc<span class="op">$</span>Expected, ncCC89, <span class="dt">zero.policy=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb29-4" data-line-number="4">nc<span class="op">$</span>EB_loc &lt;-<span class="st"> </span>res<span class="op">$</span>est</a>
<a class="sourceLine" id="cb29-5" data-line-number="5">brks &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">0</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>)</a>
<a class="sourceLine" id="cb29-6" data-line-number="6">spl &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="st">"sp.text"</span>, <span class="dt">loc=</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/coordinates">coordinates</a></span>(nc)[<span class="kw"><a href="../reference/card.html">card</a></span>(ncCC89) <span class="op">==</span><span class="st"> </span><span class="dv">0</span>,], <span class="dt">txt=</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="st">"*"</span>, <span class="dv">2</span>), <span class="dt">cex=</span><span class="fl">1.2</span>)</a></code></pre></div>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/spplot">spplot</a></span>(nc, <span class="st">"EB_loc"</span>, <span class="dt">at=</span>brks, <span class="dt">col.regions=</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rev">rev</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/RColorBrewer/topics/ColorBrewer">brewer.pal</a></span>(<span class="dv">8</span>, <span class="st">"RdBu"</span>)), <span class="dt">sp.layout=</span>spl)</a></code></pre></div>
<p><img src="sids_files/figure-html/unnamed-chunk-15-1.png" width="700"> The results are shown in Figure . Like other relevant functions in <strong>spdep</strong>,<code><a href="../reference/EBlocal.html">EBlocal()</a></code> takes a <code>zero.policy</code> argument to allow missing values to be passed through. In this case, no local estimate is available for the two counties with no neighbours, marked by stars.</p>
<p>In addition to Empirical Bayes smoothing globally, used both for disease mapping and the Assun<span>c</span>ão and Reis correction to Moran’s <span class="math inline">\(I\)</span> for rates data (to shrink towards the global rate when the population at risk is small, here as a Monte Carlo test), lists of local neighbours can be used to shrink towards a local rate.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Random">set.seed</a></span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb31-2" data-line-number="2"><span class="kw"><a href="../reference/EBImoran.mc.html">EBImoran.mc</a></span>(nc<span class="op">$</span>SID74, nc<span class="op">$</span>BIR74, <span class="kw"><a href="../reference/nb2listw.html">nb2listw</a></span>(ncCC89, <span class="dt">style=</span><span class="st">"B"</span>, <span class="dt">zero.policy=</span><span class="ot">TRUE</span>), <span class="dt">nsim=</span><span class="dv">999</span>, <span class="dt">zero.policy=</span><span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## 
##  Monte-Carlo simulation of Empirical Bayes Index (mean subtracted)
## 
## data:  cases: nc$SID74, risk population: nc$BIR74
## weights: nb2listw(ncCC89, style = "B", zero.policy = TRUE)
## number of simulations + 1: 1000
## 
## statistic = 0.25789, observed rank = 1000, p-value = 0.001
## alternative hypothesis: greater</code></pre>
</div>
</div>
<div id="exploration-and-modelling-of-the-data" class="section level2">
<h2 class="hasAnchor">
<a href="#exploration-and-modelling-of-the-data" class="anchor"></a>Exploration and modelling of the data</h2>
<p>One of the first steps taken by <span class="citation">Cressie and Read (1985)</span> is to try to bring out spatial trends by dividing North Carolina up into <span class="math inline">\(4\times4\)</span> rough rectangles. Just to see how this works, let us map these rough rectangles before proceeding further (see Figure ).</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1">nc<span class="op">$</span>both &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">factor</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/paste">paste</a></span>(nc<span class="op">$</span>L_id, nc<span class="op">$</span>M_id, <span class="dt">sep=</span><span class="st">":"</span>))</a>
<a class="sourceLine" id="cb33-2" data-line-number="2">nboth &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/table">table</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/class">unclass</a></span>(nc<span class="op">$</span>both)))</a></code></pre></div>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/spplot">spplot</a></span>(nc, <span class="st">"both"</span>, <span class="dt">col.regions=</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sample">sample</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/grDevices/topics/palettes">rainbow</a></span>(nboth)))</a></code></pre></div>
<p>Cressie constructs a transformed SIDS rates variable, 1974–78, for his analyses (with co-workers). We can replicate his stem-and-leaf figure on p. 396 in the book, taken from <span class="citation">Cressie and Read (1989)</span>:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1">nc<span class="op">$</span>ft.SID74 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">sqrt</a></span>(<span class="dv">1000</span>)<span class="op">*</span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">sqrt</a></span>(nc<span class="op">$</span>SID74<span class="op">/</span>nc<span class="op">$</span>BIR74) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">sqrt</a></span>((nc<span class="op">$</span>SID74<span class="op">+</span><span class="dv">1</span>)<span class="op">/</span>nc<span class="op">$</span>BIR74))</a>
<a class="sourceLine" id="cb35-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/stem">stem</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Round">round</a></span>(nc<span class="op">$</span>ft.SID74, <span class="dv">1</span>), <span class="dt">scale=</span><span class="dv">2</span>)</a></code></pre></div>
<pre><code>## 
##   The decimal point is at the |
## 
##   0 | 9
##   1 | 111244
##   1 | 567789999
##   2 | 0011111222334444
##   2 | 55555666677778999999999
##   3 | 000111122333333344444444
##   3 | 5568999
##   4 | 013344
##   4 | 555557
##   5 | 2
##   5 | 
##   6 | 3</code></pre>
<p><img src="sids_files/figure-html/unnamed-chunk-20-1.png" width="700"></p>
<div id="medpol" class="section level3">
<h3 class="hasAnchor">
<a href="#medpol" class="anchor"></a>Median polish smoothing</h3>
<p><span class="citation">Cressie (1991, 46–48, 393–400)</span> discusses in some detail how smoothing may be used to partition the variation in the data into smooth and rough. In order to try it out on the North Carolina SIDS data set, we will use a coarse gridding into four columns and four rows given by <span class="citation">Cressie (1991, 553–54)</span>, where four grid cells are empty; these are given by variables <span><code>L_id</code></span> and <span><code>M_id</code></span> in object <span><code>nc</code></span>. Next we aggregate the number of live births and the number of SIDS cases 1974–1978 for the grid cells:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1">mBIR74 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/tapply">tapply</a></span>(nc<span class="op">$</span>BIR74, nc<span class="op">$</span>both, sum)</a>
<a class="sourceLine" id="cb37-2" data-line-number="2">mSID74 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/tapply">tapply</a></span>(nc<span class="op">$</span>SID74, nc<span class="op">$</span>both, sum)</a></code></pre></div>
<p>Using the same Freeman-Tukey transformation as is used for the county data, we coerce the data into a correctly configured matrix, some of the cells of which are empty. The <span><code>medpolish</code></span> function is applied to the matrix, being told to remove empty cells; the function iterates over the rows and columns of the matrix using <span><code>median</code></span> to extract an overall effect, row and column effects, and residuals:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1">mFT &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">sqrt</a></span>(<span class="dv">1000</span>)<span class="op">*</span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">sqrt</a></span>(mSID74<span class="op">/</span>mBIR74) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">sqrt</a></span>((mSID74<span class="op">+</span><span class="dv">1</span>)<span class="op">/</span>mBIR74))</a>
<a class="sourceLine" id="cb38-2" data-line-number="2">mFT1 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/t">t</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/matrix">matrix</a></span>(mFT, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>))</a>
<a class="sourceLine" id="cb38-3" data-line-number="3">med &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/medpolish">medpolish</a></span>(mFT1, <span class="dt">na.rm=</span><span class="ot">TRUE</span>, <span class="dt">trace.iter=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb38-4" data-line-number="4">med</a></code></pre></div>
<pre><code>## 
## Median Polish Results (Dataset: "mFT1")
## 
## Overall: 2.765802
## 
## Row Effects:
## [1] -0.728192882  0.001560182  0.861279153 -0.001560182
## 
## Column Effects:
## [1]  0.00000000 -0.03564965  0.44969186  0.00000000
## 
## Residuals:
##           [,1]      [,2]     [,3]      [,4]
## [1,] -0.089076  0.089076  0.33761 -0.089076
## [2,]  0.089076 -0.089076 -0.33761  0.089076
## [3,]  0.327702 -0.327702 -0.93746  0.327702
## [4,] -0.324994  0.324994  0.49479 -0.324994</code></pre>
<p>Returning to the factors linking rows and columns to counties, and generating matrices of dummy variables using <span><code>model.matrix</code></span>, we can calculate fitted values of the Freeman-Tukey adjusted rate for each county, and residuals by subtracting the fitted value from the observed rate. Naturally, the fitted value will be the same for counties in the same grid cell:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1">mL_id &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/model.matrix">model.matrix</a></span>(<span class="op">~</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">as.factor</a></span>(nc<span class="op">$</span>L_id) <span class="dv">-1</span>)</a>
<a class="sourceLine" id="cb40-2" data-line-number="2">mM_id &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/model.matrix">model.matrix</a></span>(<span class="op">~</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">as.factor</a></span>(nc<span class="op">$</span>M_id) <span class="dv">-1</span>)</a>
<a class="sourceLine" id="cb40-3" data-line-number="3">nc<span class="op">$</span>pred &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(med<span class="op">$</span>overall <span class="op">+</span><span class="st"> </span>mL_id <span class="op">%*%</span><span class="st"> </span>med<span class="op">$</span>row <span class="op">+</span><span class="st"> </span>mM_id <span class="op">%*%</span><span class="st"> </span>med<span class="op">$</span>col)</a>
<a class="sourceLine" id="cb40-4" data-line-number="4">nc<span class="op">$</span>mp_resid &lt;-<span class="st"> </span>nc<span class="op">$</span>ft.SID74 <span class="op">-</span><span class="st"> </span>nc<span class="op">$</span>pred</a></code></pre></div>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" data-line-number="1">cI_ft &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/pretty">pretty</a></span>(nc<span class="op">$</span>ft.SID74, <span class="dt">n=</span><span class="dv">9</span>)</a>
<a class="sourceLine" id="cb41-2" data-line-number="2">pal_ft &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/grDevices/topics/colorRamp">colorRampPalette</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/RColorBrewer/topics/ColorBrewer">brewer.pal</a></span>(<span class="dv">6</span>, <span class="st">"YlOrBr"</span>))(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(cI_ft)<span class="op">-</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb41-3" data-line-number="3">p1 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/spplot">spplot</a></span>(nc, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"ft.SID74"</span>), <span class="dt">col.regions=</span>pal_ft, <span class="dt">at=</span>cI_ft, <span class="dt">col=</span><span class="st">"grey30"</span>, <span class="dt">main=</span><span class="st">"FT transformed SIDS rate"</span>)</a>
<a class="sourceLine" id="cb41-4" data-line-number="4">p2 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/spplot">spplot</a></span>(nc, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"pred"</span>), <span class="dt">col.regions=</span>pal_ft, <span class="dt">at=</span>cI_ft, <span class="dt">col=</span><span class="st">"grey30"</span>, <span class="dt">main=</span><span class="st">"Median-polish fit"</span>)</a>
<a class="sourceLine" id="cb41-5" data-line-number="5">atn &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/pretty">pretty</a></span>(nc<span class="op">$</span>mp_resid[nc<span class="op">$</span>mp_resid <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span>])</a>
<a class="sourceLine" id="cb41-6" data-line-number="6">atp &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/pretty">pretty</a></span>(nc<span class="op">$</span>mp_resid[nc<span class="op">$</span>mp_resid <span class="op">&gt;=</span><span class="st"> </span><span class="dv">0</span>])</a>
<a class="sourceLine" id="cb41-7" data-line-number="7">pal &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rev">rev</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/RColorBrewer/topics/ColorBrewer">brewer.pal</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(atn<span class="dv">-1</span>), <span class="st">"YlOrRd"</span>)), <span class="kw"><a href="https://www.rdocumentation.org/packages/RColorBrewer/topics/ColorBrewer">brewer.pal</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(atp[<span class="op">-</span><span class="dv">1</span>]), <span class="st">"YlGnBu"</span>)[<span class="op">-</span><span class="dv">1</span>])</a>
<a class="sourceLine" id="cb41-8" data-line-number="8">p3 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/spplot">spplot</a></span>(nc, <span class="st">"mp_resid"</span>, <span class="dt">at=</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(atn, atp[<span class="op">-</span><span class="dv">1</span>]), <span class="dt">col.regions=</span>pal, <span class="dt">col=</span><span class="st">"grey30"</span>, <span class="dt">main=</span><span class="st">"Median-polish residuals"</span>)</a>
<a class="sourceLine" id="cb41-9" data-line-number="9"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(p1, <span class="dt">split=</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">3</span>), <span class="dt">more=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb41-10" data-line-number="10"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(p2, <span class="dt">split=</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">3</span>), <span class="dt">more=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb41-11" data-line-number="11"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(p3, <span class="dt">split=</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">3</span>), <span class="dt">more=</span><span class="ot">FALSE</span>)</a></code></pre></div>
<p>Figure  shows the median polish smoothing results as three maps, the observed Freeman-Tukey transformed SIDS rates, the fitted smoothed values, and the residuals. In addition, a plot for the median polish object is also shown, plotting the smooth residuals against the outer product of the row and column effects divided by the overall effect, which would indicate a lack of additivity between row and column if this was the case — this is more relevant for analysis of tables of covariates rather than geographical grids.</p>
</div>
<div id="car-model-fitting" class="section level3">
<h3 class="hasAnchor">
<a href="#car-model-fitting" class="anchor"></a>CAR model fitting</h3>
<p>We will now try to replicate three of the four models fitted by <span class="citation">(Cressie and Chan 1989)</span> to the transformed rates variable. The first thing to do is to try to replicate their 30 mile distance between county seats neighbours, which almost works. From there we try to reconstruct three of the four models they fit, concluding that we can get quite close, but that a number of questions are raised along the way.</p>
<p>Building the weights is much more complicated, because they use a combination of distance-metric and population-at-risk based weights, but we can get quite close <span class="citation">(see also Kaluzny et al. 1996)</span>:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" data-line-number="1">sids.nhbr30.dist &lt;-<span class="st"> </span><span class="kw"><a href="../reference/nbdists.html">nbdists</a></span>(ncCC89, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/cbind">cbind</a></span>(nc<span class="op">$</span>east, nc<span class="op">$</span>north))</a>
<a class="sourceLine" id="cb42-2" data-line-number="2">sids.nhbr &lt;-<span class="st"> </span><span class="kw"><a href="../reference/listw2sn.html">listw2sn</a></span>(<span class="kw"><a href="../reference/nb2listw.html">nb2listw</a></span>(ncCC89, <span class="dt">glist=</span>sids.nhbr30.dist, <span class="dt">style=</span><span class="st">"B"</span>, <span class="dt">zero.policy=</span><span class="ot">TRUE</span>))</a>
<a class="sourceLine" id="cb42-3" data-line-number="3">dij &lt;-<span class="st"> </span>sids.nhbr[,<span class="dv">3</span>]</a>
<a class="sourceLine" id="cb42-4" data-line-number="4">n &lt;-<span class="st"> </span>nc<span class="op">$</span>BIR74</a>
<a class="sourceLine" id="cb42-5" data-line-number="5">el1 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Extremes">min</a></span>(dij)<span class="op">/</span>dij</a>
<a class="sourceLine" id="cb42-6" data-line-number="6">el2 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">sqrt</a></span>(n[sids.nhbr<span class="op">$</span>to]<span class="op">/</span>n[sids.nhbr<span class="op">$</span>from])</a>
<a class="sourceLine" id="cb42-7" data-line-number="7">sids.nhbr<span class="op">$</span>weights &lt;-<span class="st"> </span>el1<span class="op">*</span>el2</a>
<a class="sourceLine" id="cb42-8" data-line-number="8">sids.nhbr.listw &lt;-<span class="st"> </span><span class="kw"><a href="../reference/listw2sn.html">sn2listw</a></span>(sids.nhbr)</a></code></pre></div>
<p>The first model (I) is a null model with just an intercept, the second (II) includes all the 12 parcels of contiguous counties in 4 east-west and 4 north-south bands, while the fourth (IV) includes the transformed non-white birth-rate:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" data-line-number="1">nc<span class="op">$</span>ft.NWBIR74 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">sqrt</a></span>(<span class="dv">1000</span>)<span class="op">*</span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">sqrt</a></span>(nc<span class="op">$</span>NWBIR74<span class="op">/</span>nc<span class="op">$</span>BIR74) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">sqrt</a></span>((nc<span class="op">$</span>NWBIR74<span class="op">+</span><span class="dv">1</span>)<span class="op">/</span>nc<span class="op">$</span>BIR74))</a></code></pre></div>
<p>Cressie identifies Anson county as an outlier, and drops it from further analysis. Because the weights are constructed in a complicated way, they will be subsetted by dropping the row and column of the weights matrix:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" data-line-number="1">lm_nc &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/lm">lm</a></span>(ft.SID74 <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data=</span>nc)</a>
<a class="sourceLine" id="cb44-2" data-line-number="2">outl &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/which.min">which.max</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/influence.measures">rstandard</a></span>(lm_nc))</a>
<a class="sourceLine" id="cb44-3" data-line-number="3"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/character">as.character</a></span>(nc<span class="op">$</span>names[outl])</a></code></pre></div>
<pre><code>## character(0)</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" data-line-number="1">W &lt;-<span class="st"> </span><span class="kw"><a href="../reference/nb2mat.html">listw2mat</a></span>(sids.nhbr.listw)</a>
<a class="sourceLine" id="cb46-2" data-line-number="2">W<span class="fl">.4</span> &lt;-<span class="st"> </span>W[<span class="op">-</span>outl, <span class="op">-</span>outl]</a>
<a class="sourceLine" id="cb46-3" data-line-number="3">sids.nhbr.listw<span class="fl">.4</span> &lt;-<span class="st"> </span><span class="kw"><a href="../reference/mat2listw.html">mat2listw</a></span>(W<span class="fl">.4</span>)</a>
<a class="sourceLine" id="cb46-4" data-line-number="4">nc2 &lt;-<span class="st"> </span>nc[<span class="op">!</span>(<span class="dv">1</span><span class="op">:</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(nc<span class="op">$</span>CNTY_ID) <span class="op">%in%</span><span class="st"> </span>outl),]</a></code></pre></div>
<p>It appears that both numerical issues (convergence in particular) and uncertainties about the exact spatial weights matrix used make it difficult to reproduce the results of <span class="citation">Cressie and Chan (1989)</span>, also given in <span class="citation">Cressie (1991)</span>. We now try to replicate them for the null weighted CAR model (Cressie has intercept 2.838, <span class="math inline">\(\hat{\theta}\)</span> 0.833, for k=1):</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" data-line-number="1">ecarIaw &lt;-<span class="st"> </span><span class="kw"><a href="../reference/spautolm.html">spautolm</a></span>(ft.SID74 <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data=</span>nc2, <span class="dt">listw=</span>sids.nhbr.listw<span class="fl">.4</span>, <span class="dt">weights=</span>BIR74, <span class="dt">family=</span><span class="st">"CAR"</span>)</a>
<a class="sourceLine" id="cb47-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary</a></span>(ecarIaw)</a></code></pre></div>
<pre><code>## 
## Call: 
## spautolm(formula = ft.SID74 ~ 1, data = nc2, listw = sids.nhbr.listw.4, 
##     weights = BIR74, family = "CAR")
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -2.010292 -0.639658 -0.062209  0.443549  2.018065 
## 
## Coefficients: 
##             Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept) 2.945323   0.095135  30.959 &lt; 2.2e-16
## 
## Lambda: 0.86814 LR test value: 22.83 p-value: 1.7701e-06 
## Numerical Hessian standard error of lambda: 0.04838 
## 
## Log likelihood: -118.8432 
## ML residual variance (sigma squared): 1266.5, (sigma: 35.588)
## Number of observations: 99 
## Number of parameters estimated: 3 
## AIC: 243.69</code></pre>
<p>The spatial parcels model also seems to work, with Cressie’s <span class="math inline">\(\hat{\theta}\)</span> 0.710, and the other coefficients agreeing more or less by rank:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" data-line-number="1">ecarIIaw &lt;-<span class="st"> </span><span class="kw"><a href="../reference/spautolm.html">spautolm</a></span>(ft.SID74 <span class="op">~</span><span class="st"> </span>both <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data=</span>nc2, <span class="dt">listw=</span>sids.nhbr.listw<span class="fl">.4</span>, <span class="dt">weights=</span>BIR74, <span class="dt">family=</span><span class="st">"CAR"</span>)</a>
<a class="sourceLine" id="cb49-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary</a></span>(ecarIIaw)</a></code></pre></div>
<pre><code>## 
## Call: 
## spautolm(formula = ft.SID74 ~ both - 1, data = nc2, listw = sids.nhbr.listw.4, 
##     weights = BIR74, family = "CAR")
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.55896 -0.46338 -0.02035  0.38935  2.05682 
## 
## Coefficients: 
##         Estimate Std. Error z value  Pr(&gt;|z|)
## both1:2  2.06223    0.20016 10.3031 &lt; 2.2e-16
## both1:3  2.91823    0.14139 20.6400 &lt; 2.2e-16
## both1:4  4.11486    0.29939 13.7439 &lt; 2.2e-16
## both2:1  2.57650    0.26905  9.5762 &lt; 2.2e-16
## both2:2  2.17403    0.18222 11.9305 &lt; 2.2e-16
## both2:3  2.67397    0.15329 17.4443 &lt; 2.2e-16
## both2:4  3.11361    0.24699 12.6062 &lt; 2.2e-16
## both3:1  2.94400    0.29893  9.8486 &lt; 2.2e-16
## both3:2  2.65391    0.14098 18.8250 &lt; 2.2e-16
## both3:3  2.91619    0.17099 17.0552 &lt; 2.2e-16
## both3:4  3.20425    0.20349 15.7468 &lt; 2.2e-16
## both4:3  3.80286    0.20806 18.2781 &lt; 2.2e-16
## 
## Lambda: 0.2109 LR test value: 1.3088 p-value: 0.25261 
## Numerical Hessian standard error of lambda: NaN 
## 
## Log likelihood: -99.25505 
## ML residual variance (sigma squared): 891.48, (sigma: 29.858)
## Number of observations: 99 
## Number of parameters estimated: 14 
## AIC: 226.51</code></pre>
<p>Finally, the non-white model repeats Cressie’s finding that much of the variance of the transformed SIDS rate for 1974–8 can be accounted for by the transformed non-white birth variable (Cressie intercept 1.644, <span class="math inline">\(\hat{b}\)</span> 0.0346, <span class="math inline">\(\hat{\theta}\)</span> 0.640 — not significant):</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" data-line-number="1">ecarIVaw &lt;-<span class="st"> </span><span class="kw"><a href="../reference/spautolm.html">spautolm</a></span>(ft.SID74 <span class="op">~</span><span class="st"> </span>ft.NWBIR74, <span class="dt">data=</span>nc2, <span class="dt">listw=</span>sids.nhbr.listw<span class="fl">.4</span>, <span class="dt">weights=</span>BIR74, <span class="dt">family=</span><span class="st">"CAR"</span>)</a>
<a class="sourceLine" id="cb51-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary</a></span>(ecarIVaw)</a></code></pre></div>
<pre><code>## 
## Call: 
## spautolm(formula = ft.SID74 ~ ft.NWBIR74, data = nc2, listw = sids.nhbr.listw.4, 
##     weights = BIR74, family = "CAR")
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.99056 -0.44858  0.15468  0.60623  1.95541 
## 
## Coefficients: 
##              Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept) 1.4371519  0.2252729  6.3796 1.775e-10
## ft.NWBIR74  0.0408354  0.0062919  6.4902 8.572e-11
## 
## Lambda: 0.22391 LR test value: 1.1577 p-value: 0.28194 
## Numerical Hessian standard error of lambda: 0.5539 
## 
## Log likelihood: -114.0376 
## ML residual variance (sigma squared): 1201.5, (sigma: 34.663)
## Number of observations: 99 
## Number of parameters estimated: 4 
## AIC: 236.08</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" data-line-number="1">nc2<span class="op">$</span>fitIV &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/fitted.values">fitted.values</a></span>(ecarIVaw)</a></code></pre></div>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/spplot">spplot</a></span>(nc2, <span class="st">"fitIV"</span>, <span class="dt">cuts=</span><span class="dv">12</span>, <span class="dt">col.regions=</span><span class="kw"><a href="https://www.rdocumentation.org/packages/grDevices/topics/gray.colors">grey.colors</a></span>(<span class="dv">13</span>, <span class="fl">0.9</span>, <span class="fl">0.3</span>))</a></code></pre></div>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" data-line-number="1">ecarIawll &lt;-<span class="st"> </span><span class="kw"><a href="../reference/spautolm.html">spautolm</a></span>(ft.SID74 <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data=</span>nc2, <span class="dt">listw=</span>sids.nhbr.listw<span class="fl">.4</span>, <span class="dt">weights=</span>BIR74, <span class="dt">family=</span><span class="st">"CAR"</span>, <span class="dt">llprof=</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="op">-</span><span class="fl">0.1</span>, <span class="fl">0.9020532358</span>, <span class="dt">length.out=</span><span class="dv">100</span>))</a>
<a class="sourceLine" id="cb55-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(ll <span class="op">~</span><span class="st"> </span>lambda, ecarIawll<span class="op">$</span>llprof, <span class="dt">type=</span><span class="st">"l"</span>)</a></code></pre></div>
<p><img src="sids_files/figure-html/unnamed-chunk-32-1.png" width="700"></p>
</div>
</div>
<div id="references" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<div id="refs" class="references">
<div id="ref-anselin+syabri+smirnov:2002">
<p>Anselin, Luc, Ibnu Syabri, and Oleg Smirnov. 2002. “Visualizing Multivariate Spatial Correlation with Dynamically Linked Windows.” In <em>University of California, Santa Barbara. CD-ROM</em>.</p>
</div>
<div id="ref-bailey+gatrell:1995">
<p>Bailey, T. C., and A. C. Gatrell. 1995. <em>Interactive Spatial Data Analysis</em>. Harlow: Longman.</p>
</div>
<div id="ref-choynowski:1959">
<p>Choynowski, M. 1959. “Maps Based on Probabilities.” <em>Journal of the American Statistical Association</em> 54: 385–88.</p>
</div>
<div id="ref-cressie:1991">
<p>Cressie, N. 1991. <em>Statistics for Spatial Data</em>. New York: Wiley.</p>
</div>
<div id="ref-cressie+chan:1989">
<p>Cressie, N., and N. H. Chan. 1989. “Spatial Modelling of Regional Variables.” <em>Journal of the American Statistical Association</em> 84: 393–401.</p>
</div>
<div id="ref-cressie+read:1985">
<p>Cressie, N., and T. R. C. Read. 1985. “Do Sudden Infant Deaths Come in Clusters?” <em>Statistics and Decisions</em> Supplement Issue 2: 333–49.</p>
</div>
<div id="ref-cressie+read:1989">
<p>———. 1989. “Spatial Data-Analysis of Regional Counts.” <em>Biometrical Journal</em> 31: 699–719.</p>
</div>
<div id="ref-gomez-rubio+ferrandiz+lopez:2003">
<p>Gómez-Rubio, V., J. Ferrándiz-Ferragud, and A. López-Quílez. 2005. “Detecting Clusters of Disease with R.” <em>Journal of Geographical Systems</em> 7: 189–206.</p>
</div>
<div id="ref-kaluznyetal:1996">
<p>Kaluzny, S. P., S. C. Vega, T. P. Cardoso, and A. A. Shelly. 1996. <em>S-PLUS SPATIALSTATS User’s Manual Version 1.0</em>. Seattle: MathSoft Inc.</p>
</div>
<div id="ref-marshall:1991">
<p>Marshall, R. M. 1991. “Mapping Disease and Mortality Rates Using Empirical Bayes Estimators.” <em>Applied Statistics</em> 40: 283–94.</p>
</div>
<div id="ref-symonsetal:1983">
<p>Symons, M. J., R. C. Grimson, and Y. C. Yuan. 1983. “Clustering of Rare Events.” <em>Biometrics</em> 39: 193–205.</p>
</div>
</div>
</div>
<div class="footnotes">
<hr>
<ol>
<li id="fn1"><p>These data were taken with permission from a now-offline link: [sal.agecon.uiuc.edu/datasets/sids.zip].<a href="#fnref1" class="footnote-back">↩</a></p></li>
</ol>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#introduction">Introduction</a></li>
      <li><a href="#getting-the-data-into-r">Getting the data into R</a></li>
      <li><a href="#exploration-and-modelling-of-the-data">Exploration and modelling of the data</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Roger Bivand.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
